### ISSUE TITLE
ggplot2?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/oilabs-tidy#1]
The project is called this `dplyr` but what about `ggplot2`? Are others in favor of converting the plots to ggplot2 as well?

**Pros:**
Easier to make multivariable plots
Default look is a lot more this century

**Cons:**
Harder to customize -- though we do very little customization of plots in the labs anyay

**Comment by andrewpbray** [comment]
I'm in favor of giving it a try.

**Comment by beanumber** [comment]
I think the `lattice` plots are better for intro students. They emphasize the formula interface, which I think is instructive, and they still look way better than `base` graphics. `ggplot2` introduces a whole 'nother level of complexity. I'm starting to see the virtue of `ggplot2` for data science, but in intro stats I've been happy with `lattice`. 

The only real downside to `lattice` is that if you want to do something other than a standard statistical plot, it can be very difficult. But there are only one or two instances of this in the labs anyway. 

Also, I've already written the `lattice` plots into the [`mosaic` labs](https://github.com/beanumber/oiLabs-mosaic), so the work is already done -- I'd be happy to push the changes upstream.

**Comment by andrewpbray** [comment]
One thing that bugs me about lattice is the syntax for univariate visualization:

`histogram(~y)`

Cause that's always been unintuitive to me. Another minor thing: the default palette in lattice makes things looks dated to me.

**Comment by mine-cetinkaya-rundel** [comment]
I favor `ggplot2` over `lattice`. For students wanting to go further with stats after the intro course `ggplot2` I feel like will be a lot more useful. I also think TAs will likely be more familiar with `ggplot2` than `lattice` as well.

**Comment by andrewpbray** [comment]
I think one thing to realize about this fork is that we should really be designing it for exactly how we'd like the students to be learning and using R. Because unlike the base R labs, which are designed for a general audience, these can be much more tailored to our specific use/vision.

**Comment by andrewpbray** [comment]
I'm interested in giving `ggplot2` a try. I agree that it introduces a different syntax that was certainly a challenge for me to pick up. It might be less of an issue, though, with students for whom this is all brand new.

We might also gain some ground by emphasizing the dplyr chain for organizing data manipulation and it's parallels to adding layers to a ggplot.  Or . . . that might make things more confusing. Only one way to find out!

**Comment by mine-cetinkaya-rundel** [comment]
I'm interested in giving `ggplot2` a try too.

I think the "different" syntax won't be an issue for the students, to them it's all different/new anyway. I taught another class last year with ggplot2 from the beginning, and it was only a challenge for me at times, but not really for the students.

**Comment by beanumber** [comment]
It seems like I'm outnumbered! :(

@andrewpbray But it's _not_ 

```
histogram(~y)
```

It's 

```
histogram(~x, data=df)
```

The whole point is the very `dplyr` way of thinking that you are always working with data.frames -- and not vectors. 

Also, if it helps, you can think about `~x`, since the `x` variable goes on the horizontal axis in a histogram, and the vertical axis is implicit, so there is no `y` variable. Incidentally, this is also the `ggplot2` way of thinking about this...(right?)
[Aside: from a technical POV, the `~` is necessary to make R understand this as a formula.]

I agree that the palette is not great, but we could always create a better one and include it in the package. FWIW, I find the default palette in `ggplot2` to be even worse (hate the gray background).

@mine-cetinkaya-rundel So, you have an intro student and you ask them to make a histogram of the distance variable. And the solution is:

```
library(dplyr)
ggplot(cars, aes(x = dist)) + geom_histogram()
```

and not

```
library(lattice)
histogram(~dist, data=cars)
```

???

I agree that the former emphasizes the conceptual ideas behind composing data graphics from primitive elements, and mapping variables to specific graphical elements. I really like this idea and for these reasons I'm planning to use it with my data science students. 

The latter emphasizes the conceptual understanding of what _kind_ of plot you are trying to make. This is why I think `lattice` is great for making canned statistical plots (e.g. histograms, densityplots, scatterplots, boxplots, etc.) but challenging for making customized graphics. 

So maybe the way to frame the question is should intro stats students be making standard statistical plots or customized graphics?

**Comment by beanumber** [comment]
Assuming I lose this argument, what about just `oiLabs-hadleyverse` for `dplyr + ggplot2`? I might keep `oiLabs-mosaic` for `mosaic + lattice`.

**Comment by nicholasjhorton** [comment]
I'm planning to stick with lattice for intro stats.  Being able to support a consistent modeling interface for descriptive statistics, graphics, and linear models is a big win:

require(mosaic)
favstats(~ age, data=HELPrct)
mean(~ age, data=HELPrct)
densityplot(~ age, data=HELPrct)

favstats(age ~ substance, data=HELPrct)
lm(age ~ substance, data=HELPrct)
bwplot(age ~ substance, data=HELPrct)

**Comment by rudeboybert** [comment]
Let me preface my reply by saying I don't have much experience with lattice.

I'm in favor of ggplot. ggplot saved my bacon a few times for consulting
sessions with students I was ill-prepared for or did not understand what
was being asked. I asked the students themselves identify all the elements
of the ggplot2 grammar of graphics and often they could answer their own
questions. So while there are a multitude of graphics packages present (and
future) one can consider, I think the language/package agnostic principles
underlying ggplot are strong enough to make it the winner.

As for the cons, I think the 'nother level of complexity can be overcome
for an intro stats audience if we do not conflate the following bolded
notions:
1. _The Grammar of Graphics_: data, aesthetics, geoms.
2. _ggplot2 specifics_ i.e. the customizations Mine was referring to.
   For example the geom="stat" vs geom="identity" in creating barchats was one
   my data science students got hung up on. scales are another thing I myself
   still haven't mastered.

IMO the former would be best done in lecture/written homework than lab. We
explicitly lay out the grammar, construct/sketch new graphics on
blackboard/paper, deconstruct existing ones, etc.  The latter is what would
be focused on in labs all while telling the students we're only scratching
the surface of possible customizations.

I think Ben's question is the right one we need to answer: how abstract do
we want to go? This is definitely a function of how strong the audience is.
So maybe the question can be recast as who are we teaching with these labs?

On Mon, Jul 20, 2015 at 10:21 AM, Nicholas Horton notifications@github.com
wrote:

> I'm planning to stick with lattice for intro stats. Being able to support
> a consistent modeling interface for descriptive statistics, graphics, and
> linear models is a big win:
> 
> require(mosaic)
> favstats(~ age, data=HELPrct)
> mean(~ age, data=HELPrct)
> densityplot(~ age, data=HELPrct)
> 
> favstats(age ~ substance, data=HELPrct)
> lm(age ~ substance, data=HELPrct)
> bwplot(age ~ substance, data=HELPrct)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andrewpbray/oiLabs-dplyr/issues/1#issuecomment-122900967
> .

## 

"Master technique but let the spirit prevail."

**Comment by dtkaplan** [comment]
Some reasons _not_ to use `ggplot2` in an intro stats course:
1. Students have a harder time getting started.  This is not conjecture.  I've taught both with lattice and `ggplot()`.  To me, it's very important to empower students from the beginning; show that they can use the software successfully and avoid any early frustration. (Frustration later on, when the student knows that he or she has been successful earlier, is OK!)
2. The flexibility that `ggplot()` offers in constructing custom graphics is not typically made use of in an intro stats course.  
3. There are categorical mistakes that are possible with `ggplot()` that don't happen with `lattice`, e.g.

``` r
> ggplot(CPS85, aes(x=age, y=wage, color=sex)) + geom_point() + geom_histogram()
Error : Mapping a variable to y and also using stat="bin".
  With stat="bin", it will attempt to set the y value to the count of cases in each group.
  This can result in unexpected behavior and will not be allowed in a future version of ggplot2.
  If you want y to represent counts of cases, use stat="bin" and don't map a variable to y.
  If you want y to represent values in the data, use stat="identity".
  See ?geom_bar for examples. (Defunct; last used in version 0.9.2)
```

Yes, you can learn from such an error, but it's going to be hard for intro students to get much out of an error message like this.

I'd suggest that if you want to use `ggplot()` as an engine, use an interface to it that looks like lattice.

**Comment by swang87** [comment]
I'm in the lattice camp as well. ggplot() operates unlike any other R functions that we typically use. It's extensible, looks nice, but boy is that learning curve steep! As others have pointed out above, just to get a simple plot multiple lines are oftentimes required (particularly if you want to manipulate legends and titles). The amount of cringing I see in class is directly related to how much code is needed. 

Googling for help on ggplot also yields unhelpful results because ggplot2 has evolved so much over time that some answers on StackExchange, for example, are no longer applicable.

**Comment by AmeliaMN** [comment]
I'm torn here. In my personal work, I use `ggplot2` almost exclusively, and it feels more flexible to me. But, with the Introduction to Data Science class we've been running in LA high schools, we use `mosaic` + `lattice`, and there is a lot to be said for pulling that formula syntax through the entire curriculum. 

`lattice` still doesn't feel as natural to me, but some (all?) of that is my relative lack of experience with it. By introducing students to it from the start, it will feel natural to them. But, the same could be said of `ggplot2`, and I think that introducing it immediately would add the `ggplot2` learning curve in with the rest of the `R` learning curve and we might end up with super-fluent `ggplot2` practitioners. 

I like @beanumber's idea of having two branches, one for each syntax, so that people could choose.

**Comment by rpruim** [comment]
I suggest that you complete the _minimal R_ exercise.  Write a little function to scrape out all of the commands you introduce.  Organize them twice, once by topic and once by syntax.  Look for ways to keep the list as short and coherent as possible while still getting the job done.

I started using `lattice` because it was the most familiar option to me.  (I predate `ggplot` and preferred lattice to base graphics.)   I keep using it with Intro students because of the exercise above.  I can get every thing I need using `lattice`, and coupled with the `mosaic` package, a large majority of the code I use fits into one simple template:

``` r
goal( y ~ x, data = mydata, ...)
```

Truth be told, sometimes `y ~ x` becomes `~ x` because `y` is not required or `y ~ x | z` so I can panel by a covariate.  But pretty soon it just becomes

``` r
goal( formula, data = mydata, ... )
```

I keep the use of `...` to a minimum (`groups =` is an important component there).

This one template gets me numerical summaries, graphical summaries, and linear models all in a coherent package.  That's a lot of creative power for very little syntactic volume.  If you are going to need formulas for modeling anyway, you get numerical and graphical summaries essentially for free (in terms of cognative load).  In fact, it is better than free because students can master the formulas on simpler things like numerical and graphical summaries rather than having to learn about formulas in the context of modeling, which is a bit more abstract.  

Once students are comfortable with these things, one can move on to other templates/structures/etc.  Whether that is in the Intro course or in another course will depend on the students and on the course goals.

We just ran a workshop for faculty last week.  In about 1.5 hours, we took people who had never used R or RStudio before and were not statisticians and had them making graphical and numerical summaries using `lattice` and `mosaic`.  The next day we introduced `ggplot2` and `dplyr`.  They are more flexible in some ways, but even for faculty, it takes longer to do even simple things and there is a significant investment required to really take advantage of the extra power.

A note on `dplyr` and `ggplot2`:  They don't exactly play nicely together.  `ggplot2` does not use the chaining syntax of `dplyr` and the alternation between `+` and `%>%` is just one more little hurdle.  `ggvis`, while not as feature rich, plays much better (and has an overall better design).

**Comment by andrewpbray** [comment]
This is all very useful feedback - thanks all.

Having that unified syntax through informal modeling (graphics) and formal linear models is certainly a big plus in favor of `lattice`. I still have some reservations, though, that that particular syntax has it's own cost. If you only use the formula interface for formal modeling, you can explain it to students as "a linear model for y as a function of x1 and x2". Using the formula interface for univariate graphics invalidates that pattern (@rpruim, I think we ran through this discussion on an email thread awhile back?).

The biggest plus in favor of `ggplot2` is probably its popularity and its extensibility. In terms of the lack of conciseness of the syntax, I think that could be addressed by using `qplot()` (I _think_ all of the graphics in these labs can be constructed with that command, but I'll have to check). That'd also solve the confusion of these two strange operators `%>%` and `+` that seem so similar yet so different.

I like @beanumber / @AmeliaMN 's thought to develop two sets of labs here, one with `lattice` and one with `ggplot2`. Ben, I'm not sure if it'd be easier for the `lattice` one to happen as a branch on your `mosaic` fork to incorporate more `dplyr` or if it'd be easier to fork the repo here as it gets developed and then incorporate more `lattice`. For the repo that uses `ggplot2`, to summarize the changes that I'm thinking of (relative to the base R labs):
- replace all square brackets with `dplyr`.
- replace base R graphics with `qplot()`.
- replace `for()` with `do()` imported from `mosaic`.
- (possibly) incorporate a shiny applet into the sampling distributions lab as a stepping stone into using `do()`.

I haven't taught with _either_ `lattice` or `ggplot2`, so I'm looking forward to giving it a go.

**Comment by beanumber** [comment]
So these four bullets would be in the `oiLabs-dplyr` repository?
If so, then it sounds like the main differences between `oiLabs-mosaic` and `oiLabs-dplyr` would be the use of `lattice` graphics instead of `qplot()`. [Thoughts on that @rpruim @dtkaplan @nicholasjhorton ??]

There will be small differences for things like groupwise means.

```
library(mosaic)
mean(mpg ~ cyl, data=mtcars)
```

vs. 

```
library(dplyr)
mtcars %>%
  group_by(cyl) %>%
  summarise(avg = mean(mpg))
```

If you make these changes, I will switch `oiLabs-mosaic` from a fork of `oiLabs` to a fork of `oiLabs-dplyr`. 

But in any case, I applaud your efforts on those four bullets and am happy to contribute.
