### ISSUE TITLE
Normal Distribution Lab

### ISSUE THREAD

**Issue by rudeboybert** [OpenIntroStat/oilabs-tidy#24]
Two notes in the [Normal Distribution](https://github.com/rudeboybert/oiLabs-dplyr-ggplot/blob/master/normal_distribution/normal_distribution.Rmd#evaluating-the-normal-distribution) lab:
- The qqplots should have diagonal lines indicating when observed quantiles are exactly equal to theoretical normal quantiles. For instance in the mosaic version of the labs they do. Not sure if this is best achieved via ggplot commands, or a wrapper function.
- Also almost all students got tripped up in trying to plot the qqplot of `sim_norm`. They would replace `data` and not `sample` in the command `qplot(sample = hgt, data = fdims, stat = "qq")`, not realizing that since `sim_norm` is a standalone vector (and not a variable within a data frame) they should be using `qplot(sample = sim_norm, stat = "qq")`. Perhaps assign `sim_norm` to the data frame `fdims`?

**Comment by mine-cetinkaya-rundel** [comment]
How many people are still using this lab? I don't, hence the most recent dplyr-ggplot versions of labs that are based on my labs do not have this lab. If there is sufficient interest to hold on to the lab someone needs to take on updating it (I'd rather it not be me since I haven't used it in years and others might have more experience with what works). If the consensus is that it's not the most interesting / widely used lab, I think we can remove it. Thoughts? @andrewpbray @beanumber @rudeboybert

**Comment by beanumber** [comment]
@mine-cetinkaya-rundel what do you do instead? Just skip this one? I have been using it blindly, but if you have something better please let us know.

**Comment by mine-cetinkaya-rundel** [comment]
@beanumber I've just been skipping it. The reason is that I keep the probability section short so skipping this makes the pacing easier for me for syncing weekly labs with class content. I use 2-3 lab sessions / semester as "work on project" and a 1-2 always get wasted somehow (holidays, drop/add, first week of classes where we use the time to collect information for team formation, etc.) so skipping it is what has worked for me.

**Comment by beanumber** [comment]
I have been using this. `bdims` does not appear to be in the `oilabs` package!

**Comment by mine-cetinkaya-rundel** [comment]
Was "this" supposed to be a link? 

Not sure why `bdims` isn't there, it should be. @andrewpbray? We can definitely put it back in.

**Comment by mine-cetinkaya-rundel** [comment]
@beanumber ok `bdims` is now back in the package (i got worried that i accidentally removed it during development, i shouldn't have but not sure and didn't go back thru commit history)

**Comment by mine-cetinkaya-rundel** [comment]
Since we abandoned the `qplot()` syntax I believe this is no longer relevant, so I'll close.
