### ISSUE TITLE
Inference for numerical data lab

### ISSUE THREAD

**Issue by rudeboybert** [OpenIntroStat/oilabs-tidy#28]
In the [inf for numerical data lab](https://github.com/andrewpbray/oiLabs-dplyr-ggplot/blob/master/inf_for_numerical_data/inf_for_numerical_data.Rmd#exploratory-analysis) The dplyr chain 

```
nc %>%
  group_by(habit) %>%
  summarize(mean(weight))
```

does not work for other numerical variables (such as `weeks`, `gained`, `visits`) due to missing data. Do we want to scrub the data set of rows with missing values, or do we want to complicate the 3rd element in the chain by 

```
summarize(mean(weight, na.rm=TRUE))
```

I vote for the latter since this is a teachable moment about using real data.

**Comment by andrewpbray** [comment]
Agreed with the `na.rm = TRUE`. It's unfortunate that R's treatment of na's is inconsistent, but still an important thing to make the aware of generally. This comes up, too, in the flights data set.

**Comment by rudeboybert** [comment]
Ok, I'll make a pull request later and bake in a mini-lesson about missing data.

**Comment by rpruim** [comment]
I'm not as bothered about R's `na.rm` behavior as most, I guess.  Plowing on without noticing when there is missing data is a bad idea.  Whatever you do, if you really want to talk about missing data, then just appending `na.rm=TRUE` is NOT the solution.  Your summary should count the missing values and display how many there are.  Otherwise, you are using the teachable moment to teach the wrong thing.

See `mosaic::favstats()` for a reasonable solution to this issue.  Unfortunately, `summarise()` doesn't allow you to provide a vector of values all at once, and I don't think there is a version of `n()` that counts only non-missing values.  (But keep an eye on https://github.com/hadley/dplyr/issues/1367.)

Something along these lines is what I have in mind.  I may put something like `n_missing()` into the `mosaic` package.

``` r
n_missing <- function( ..., combine = any ) {
  M <- cbind(...)
  base::sum(apply(M, 1, function(x) combine(is.na(x))), na.rm = TRUE)
}

tally( ~is.na(Weight) + is.na(Height), data = NHANES, margins = TRUE)
##              is.na(Height)
## is.na(Weight)  TRUE FALSE Total
##         TRUE     65    13    78
##         FALSE   288  9634  9922
##         Total   353  9647 10000

NHANES %>%
  summarise(
    missing_ht = n_missing(Height),
    missing_wt = n_missing(Weight),
    missing_either = n_missing(Weight, Height),
    missing_both = n_missing(Weight, Height, combine = all)
    )
## Source: local data frame [1 x 4]
## 
##   missing_ht missing_wt missing_either missing_both
##        (int)      (int)          (int)        (int)
## 1        353         78            366           65
```

**Comment by rpruim** [comment]
It's in the beta branch of the `mosaic` package now.  The usage has changed just a bit from what's above:

``` r
  NHANES %>%
    summarise(
      mean.wt = mean(Weight, na.rm = TRUE),
      missing.Wt = n_missing(Weight),
      missing.WtAndHt = n_missing(Weight, Height, type = "all"),
      missing.WtOrHt = n_missing(Weight, Height, type = "any")
      )
## Source: local data frame [1 x 4]
## 
##   mean.wt missing.Wt missing.WtAndHt missing.WtOrHt
##     (dbl)      (int)           (int)          (int)
## 1 70.9818         78              65            366
```
