### ISSUE TITLE
Inference for categorical data lab

### ISSUE THREAD

**Issue by rudeboybert** [OpenIntroStat/oilabs-tidy#29]
In the On Your Own section, Q1.a) you ask students to "Form confidence intervals for the true proportion of atheists in both years, and determine whether they overlap." I think a better approach is via a single confidence interval on the difference in proportions.

Even though two individual confidence intervals may overlap, suggesting they are not different, the confidence interval of the difference might still suggest they are in fact different. (If you need an example of this, let me know) This is a common misinterpretation of bar plots with error bars (i.e. dynamite plots).

**Comment by rpruim** [comment]
+1

**Comment by AmeliaMN** [comment]
We just did this lab in my class and I want to second (or third!) this comment. In fact, because we have talked in lecture about inference for the difference in proportions my students were baffled about why we were forming two different CIs. Then, when Q2 asks you to find the Type I error we had a lot of conversation about what that would actually be, given that the standard errors were different, the intervals could overlap in different ways, etc. 

I encouraged my students to think about Q2 in the context of a set of tests about difference in proportions, which makes the Type I error much easier to think about. But, I think the confusion would be cleared up by changing this lab entirely to be about differences in proportions!

**Comment by mine-cetinkaya-rundel** [comment]
To be honest I have no idea how this question even made it in the release, or past any edits. And I agree it's completely wrong to do it this way. Thanks for raising the issue here so that we don't miss it in the revision stage.

**Comment by beanumber** [comment]
If memory serves this was inserted because @andrewpbray and I hadn't made it to difference of two proportions when it came time to teach this lab. But it is kind of a mess now.

**Comment by mine-cetinkaya-rundel** [comment]
This has been removed in the most recent version of the labs.
