### ISSUE TITLE
Use of `n = n()`

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/oilabs-tidy#46]
My students found this:

```
sfo_feb_flights %>%
  group_by(origin) %>%
  summarise(n = n())
```

to be really confusing. I agree. I would recommend naming the derived column `N` or `num_rows` instead of `n`, which is the name of a function!

Incidentally, I am a big believer in always counting the number of rows, so I'd also recommend putting that into every `summarise()` call out of habit.

**Comment by mine-cetinkaya-rundel** [comment]
sure, we can rename. or should we introduce the `count()` function?

i'd prefer `num_rows()` instead of `N`

**Comment by beanumber** [comment]
You mean `num_rows`? I like the `n()` function. To be clear, I'm thinking:

```
sfo_feb_flights %>%
  group_by(origin) %>%
  summarise(num_rows = n())
```

**Comment by mine-cetinkaya-rundel** [comment]
ah sorry yes, meant `num_rows` instead of `num_rows()`

**Comment by rpruim** [comment]
For what it is worth, I think `num_rows` is not a good name in most cases -- rows of what?  In the data frame where this ends up, there will be rows, but this num_rows is the number of rows in (some subset of) some other data frame.  I would stick with `n` or else name it in a way that indicates what is actually being counted (like `num_flights`).  

Since `n` is ubiquitous in statistics as the number of observations (and not dependent on the software you are using), I'm not really opposed to use `n` for this.  (See `favstats()`, for example.)

**Comment by mine-cetinkaya-rundel** [comment]
I think @beanumber meant to say `n = n()` is confusing, where the variable name and the function are the same.

I'm changing it to `n_flights = n()` in an effort to keep the var name short and specific at the same time.
